server:
  port: 8002


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimeZone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  application:
    name: jhye-spring-cloud


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002
    hostname: localhost

#info配置
info:
  app.name: jhye-springcloud
  company.name: iflytek
